### ISSUE TITLE
Question: frecvency

### ISSUE THREAD

**Issue by chinezbrun** [Pioreactor/rpi_hardware_pwm#7]
how to read this: pwm.change_frequency(25_000)?
25Hz or 25kHz? 
if answer is 25Hz what means _000?

**Comment by CamDavidsonPilon** [comment]
Hi @chinezbrun, 

It means 25khz. In Python, `25_000` is the same as `25000`. The `_` is a new Python3 feature that makes big numbers easier to read.

**Comment by chinezbrun** [comment]
thanks. all clear now. i just want to double check before run the code :)
